{
    'name': 'Emad Branch Accounting Report',
    'version': '1.0',
    'summary': 'Advanced accounting reports with branches and partner ledger support',
    'author': 'Emad Kadry - Taknia Soft',
    'website': 'https://www.taknia.com',
    'category': 'Accounting',
    'license': 'LGPL-3',
    'depends': ['account', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/accounting_report_view.xml',
        'views/partner_ledger_view.xml',
        'wizards/accounting_report_wizard.xml',
        'wizards/partner_ledger_wizard.xml',
        'reports/accounting_report_template.xml',
        'reports/partner_ledger_template.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
