{
    'name': 'Taknia Branch Management',
    'version': '1.0',
    'summary': 'Module to manage branches efficiently',
    'sequence': 10,
    'description': """Taknia Branch Management module helps manage branches, track performance, and generate reports.""",
    'category': 'Management',
    'author': 'Taknia',
    'maintainer': 'Taknia',
    'website': 'https://www.takniasoft.com',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/menus.xml',
        'views/branch_views.xml',
        'views/branch_performance_views.xml',
        'views/branch_budget_views.xml',
        'views/kpi_dashboard_views.xml',
        'views/ai_branch_advisor_views.xml',
        'views/branch_customer_analysis_views.xml',
        'views/branch_expense_analysis_views.xml',
        'views/branch_stock_analysis_views.xml',
        'views/branch_employee_analysis_views.xml',
        'views/branch_esg_analysis_views.xml',
        'views/branch_financial_health_views.xml',
        'views/branch_scoring_views.xml',
        'views/module_settings_views.xml',
        'reports/report_templates/branch_performance_template.xml',
        'reports/report_templates/branch_financial_health_template.xml',
        'reports/report_templates/branch_expense_analysis_template.xml',
        'reports/report_templates/branch_stock_analysis_template.xml',
        'reports/report_templates/branch_customer_analysis_template.xml',
        'reports/report_templates/branch_scoring_template.xml',
        'reports/report_templates/ai_recommendation_template.xml',
        'reports/report_actions/branch_performance_actions.xml',
        'reports/report_actions/branch_financial_health_actions.xml',
        'reports/report_actions/branch_expense_analysis_actions.xml',
        'reports/report_actions/branch_stock_analysis_actions.xml',
        'reports/report_actions/branch_customer_analysis_actions.xml',
        'reports/report_actions/branch_scoring_actions.xml',
        'reports/report_actions/ai_recommendation_actions.xml',
        'wizards/branch_performance_wizard.xml',
        'wizards/financial_advice_wizard.xml',
        'data/cron_jobs.xml',
        'static/src/css/custom_styles.css',
        'static/src/js/kpi_charts.js',
        'i18n/ar.po',
        'i18n/en.po',
        'README.md',
        'index.html',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}